### ISSUE TITLE
Rename "solr-extensions" Github org

### ISSUE THREAD

**Issue by tboeghk** [solr-cool/solr-cool.github.io#26]
As noted in #16 we refer to Solr plugins as packages, extensions and plugins. We should keep that straight and rename the Github org @solr-extensions. First ideas in my mind:

- __solr-plugins__
- __solr.cool__
- __solr-plugin-directory__

Ideas welcome!

**Comment by epugh** [comment]
I like solr.cool!   We have the domain name, and it's fun.

**Comment by tboeghk** [comment]
BTW, we're @solr-cool now 😎

**Comment by epugh** [comment]
The future is so bright we need shades!
